### PR TITLE
Disable by default docker repository

### PR DESCRIPTION
**Pull request by stephdl**

### CODE REVIEW

**Comment by stephdl** [comment]
The update between docker version can break the containers. After an upgrade you can find this in logs

```
dockerd: time="2020-06-06T14:34:22.486213146+02:00" level=error msg="Failed to start container f614788e206becd9b16c7081375394018afaeede485261db5ca22ef8fcb5055c: failed to listen to abstract unix socket \"/containerd-shim/moby/f614788e206becd9b16c7081375394018afaeede485261db5ca22ef8fcb5055c/shim.sock\": listen unix \x00/containerd-shim/moby/f614788e206becd9b16c7081375394018afaeede485261db5ca22ef8fcb5055c/shim.sock: bind: address already in use: unknown"
```

you can search in google with  : shim.sock: bind: address already in use: unknown


Either 

- you must restart the server
- or kill the PID of the failed container, then restart the container for example: https://github.com/moby/moby/issues/38726#issuecomment-640053011

Like this the upgrade of docker will an admin decision

`yum update --enable=docker-ce-stable`

or

```
config setprop docker enableRepository
signal-event nethserver-docker-update
```

**Comment by stephdl** [comment]
@mrmarkuz @pagaille I would like to disable the repository of docker, what do you think

**Comment by pagaille** [comment]
Fully agree. Stability is a must for me.

**Comment by thaJeztah** [comment]
Do you have more details under what circumstances this problem occurs? Is this also happening when updating minor / patch releases? Do you have a way to reproduce the problem?

**Comment by stephdl** [comment]
Hello @thaJeztah 

NethServer is a centos7 clone, we use docker with a shorewall firewall with a custom docker network `aqua` but IIRC it happened also with the docke0 that you know well.

I tested with and without the option 'live-restore' true
I updated from 
```
containerd.io-1.2.6-3.3.el7.x86_64
docker-ce-cli-19.03.8-3.el7.x86_64 
docker-ce-19.03.8-3.el7.x86_64 
```

to 

```
containerd.io-1.2.13-3.2.el7.x86_64
docker-ce-cli-19.03.11-3.el7.x86_64
ocker-ce-19.03.11-3.el7.x86_64
```


after the upgrade, the container launched by 
`docker run  -dit --name nginx-test-01 -p 9001:80 --net aqua --restart=unless-stopped nginx:alpine nginx-debug -g 'daemon off;'`

is stopped and you can find an error in /var/log/messages 

https://gist.github.com/stephdl/a17f47b6e07e34dda6b1561396e3f3ae

If I search by the ID of the container, I can see that a PID has not been killed by the upgrade

```
[root@ns7loc3 ~]# ps aux | grep '651aae34d54e'
root      1875  0.0  0.6 108744  6456 ?        Sl   20:51   0:00 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/651aae34d54eacfabb1b6651d23e2a864ff39f678ffb19990836ea639087aaf3 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
```

If you have some clues, I would be interested :)

**Review by mrmarkuz — APPROVED** [review]
It's working as expected. Docker-ce repo is disabled by default, after enabling by db prop docker-ce got updates.

**Pull request merged**
