### PR TITLE
Restart docker after shorewall

### PR DESCRIPTION
**Pull request by stephdl**

### CODE REVIEW

**Review by mrmarkuz — APPROVED** [review]
Great, it works as expected. Containers in aqua now keep talking to each other even after "systemctl restart shorewall" and "signal-event firewall-adjust" and reboot.

**Comment by stephdl** [comment]
we did not fix something, in fact if you do `shorewall restart` this is still broken, we could fix it by adding a docker restart in /etc/shorewall/started but it will be with a template.

My concern is if you remove the nethserver-docker, then the template `/etc/shorewall/started` will stay active. Honestly I am not a big fan to customize shorewall for docker :)

What do you think @mrmarkuz ?

**Comment by mrmarkuz** [comment]
I trìed it yesterday with /etc/shorewall/started and it worked with "shorewall restart" but it made systemctl restart shorewall hang.
I think it's ok to just fix the firewall-adjust event and systemd because it is mostly used.
Maybe put a line to the docs about not working "shorewall restart".

**Comment by stephdl** [comment]
> Maybe put a line to the docs about not working "shorewall restart".

I think it is quite obsolete by systemd, we use it internally with the event. I am not sure but I think really few people will use it

**Pull request merged**
